default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: daily_report_development

test:
  <<: *default
  database: daily_report_test

production:
  <<: *default
  database: daily_report_production
  username: api
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
